<?php

namespace App\Filament\Resources\ExpenseResource\Pages;

use App\Filament\Resources\ExpenseResource;
use Filament\Pages\Actions;
use Filament\Resources\Pages\ListRecords;
use Illuminate\Database\Eloquent\Builder;

class ListExpenses extends ListRecords
{
    protected static string $resource = ExpenseResource::class;

    protected function getActions(): array
    {
        return [Actions\CreateAction::make()];
    }
    protected function getHeaderWidgets(): array
    {
        return [ExpenseResource\Widgets\TotalAmount::class];
    }
    protected function getTableQuery(): Builder
    {
        $this->emit("updateTotalAmount", [
            "tags" => $this->tableFilters["tags"] ?? [],
        ]);
        return parent::getTableQuery(); // TODO: Change the autogenerated stub
    }
}
